version: "3.9"
services:
  codeforge:
    image: postgres
    restart: always
    container_name: codeforge
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: